### PR TITLE
Not using non-const reference to temporary object

### PR DESCRIPTION
**Pull request by demiurg**
This way the object is on the stack.

### CODE REVIEW

**Comment by demiurg** [comment]
Perhaps it breaks and slows things down, if chunks are consumed. In this case it's better to just not have a default temporary object?

**Comment by demiurg** [comment]
Is this open source project not being maintained anymore?

**Comment by matthewhanson** [comment]
There is currently no consistent effort on maintaining it.

**Comment by demiurg** [comment]
ok

**Pull request closed without merging**
