### PR TITLE
release v1.0.0

### PR DESCRIPTION
**Pull request by matthewhanson**
Merge into master

### CODE REVIEW

**Comment by ircwaves** [comment]
Well done!

**Comment by matthewhanson** [comment]
I pushed the v1.0.0 tag, which should be triggering a deploy to PyPi, with pre-generated swig files so it's not necessary to have swig installed.

**Comment by ircwaves** [comment]
Test coverage is looking good.

**Comment by matthewhanson** [comment]
It was higher, but then I had added new features.  Can always add more tests, time to start on version 1.1

**Pull request merged**
