### PR TITLE
fix(chunks): using numchunks didn't cover image

### PR DESCRIPTION
**Pull request by ircwaves**
I believe this is straight forward -- found in 0.3.x branch, and also exists in mainline development.

I hope the expansion/tweaks to the chunking test make sense to cover the cases.  The previous `test_GeoResource.test_chunking` didn't actually assert about the final chunk.

:+1: to @justinfisk for the help in sorting this out on the 0.3.x branch.

### CODE REVIEW

**Comment by ircwaves** [comment]
I just broke the single commit into two, so that the test demonstrates (hopefully it's been a while) the failure with one CI run, and then the fix with the second CI run.  I'll push the second commit once the checks have completed on the first commit.

**Comment by ircwaves** [comment]
Well, the 2.7 fail looks more CI config, or underlying base image for the docker build.  2df66d3 is code almost identical to 0466b6f :
```
icooke@north:~/src/gipit/gippy$ git diff 2df66d3 0466b6f
diff --git a/.gitignore b/.gitignore
index 1532d21..f6fa5cd 100644
--- a/.gitignore
+++ b/.gitignore
@@ -14,3 +14,4 @@ gippy/gippy_wrap.cpp
 gippy/algorithms.py
 gippy/algorithms_wrap.cpp
 /.vs
+venv
```
which passed before I did this break out.

**Comment by ircwaves** [comment]
Ok, @matthewhanson, i pushed a copy of develop to test if I broke something, and it is definitely not anything I did. Given that python2 is deprecated, and this works for 3, are you ok with this merging?

**Comment by ircwaves** [comment]
[this](https://circleci.com/gh/gipit/gippy/407?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) is the develop branch that I added a newline to today.

**Comment by ircwaves** [comment]
@matthewhanson -- the issue in the test_27 ci pipeline looks to be related to a change in the stack such that in the `pip install .` does not install the `gippy.py` file.  As a work around, doing a `pip install -e .` shows that this passes the test when the module is loadable.  As this only hits py2, I'm not concerned with it, but wonder what your thoughts are?

**Review by matthewhanson — APPROVED** [review]

**Pull request merged**
